version = "3.7.15"
preset=IntelliJ
maxColumn = 120

# adapted from ZIO project https://github.com/zio/zio/blob/series/2.x/.scalafmt.conf
runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
align.preset = most
align.multiline = false
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrapMaxColumn = 120
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
optIn.annotationNewlines = true
newlines.alwaysBeforeMultilineDef = false
rewrite.rules = [RedundantBraces]

project.excludePaths = ["glob:**/scalafix/input/**", "glob:**/scalafix/output/**"]

rewrite.redundantBraces.generalExpressions = false
