rules = [
  #typelevel rules
  TypelevelMapSequence,
  TypelevelAs,
  TypelevelHttp4sLiteralsSyntax,
  TypelevelIORandomUUID,

  #bultin
  DisableSyntax,
  RemoveUnused,
  ExplicitResultTypes,
  LeakingImplicitClassVal,
  NoValInForComprehension,
//  OrganizeImports,
  ProcedureSyntax,
  RedundantSyntax,
  RemoveUnused
]

#built-in scalafix
DisableSyntax.noVars = true
DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noXml = true
DisableSyntax.noDefaultArgs = false
DisableSyntax.noFinalVal = false
DisableSyntax.noFinalize = true
DisableSyntax.noValPatterns = false
DisableSyntax.noUniversalEquality = false
DisableSyntax.regex = []

ExplicitResultTypes.fetchScala3CompilerArtifactsOnVersionMismatch = true

OrganizeImports.preset = "INTELLIJ_2020_3"
