version: '3'

#dotenv: [ '.env' ]

tasks:
  clean:
    cmds:
      - rm -r backend/target
      - rm -r client/node_modules
  serve:
    dir: ./client
    cmds:
      - npm start

  build-backend:
    aliases: [build]
    deps:
      - task: setup-client
      - task: build-client
    cmds:
      - sbt ";backend/clean;backend/Universal/packageBin"

  setup-client:
    dir: ./client
    cmds:
      - npm ci
  build-client:
    cmds:
      - sbt ";clean;client/fastLinkJS"
      - cd ./client && npm run build && cd ..
    generates:
      - ./client/dist
